### ISSUE TITLE
CNN-Train-nasnet Error

### ISSUE THREAD

**Issue by EricRoberts714** [xdatacnn/imagesearch#21]
![CNN-train-nasnet error](https://user-images.githubusercontent.com/17167333/72020225-2b003e80-3220-11ea-81f6-37a78ff041d8.png)

**Comment by EricRoberts714** [comment]
Similar errors to the one attached occur for the CNN architectures nasnet, inception_resnet, vgg16, and inception_v4.

Of note, when selecting one of these four architectures, there is no option to save the model. Only the lanet architecture provides this option

**Comment by flavio86** [comment]
Fixed. Please @EricRoberts714, could you update the code and try to run again?

**Comment by EricRoberts714** [comment]
Looks like pandas is missing. This is after I performed a full re-install and re-created the environment.

After I manually installed pandas (ver. 0.25.3), I receive the following error for the lenet architecture:
 
![CNN-train-lenet_error](https://user-images.githubusercontent.com/17167333/72115254-468c4780-32fb-11ea-8408-b5b93276dca7.png)

**Comment by flavio86** [comment]
Thank you for the update @EricRoberts714. Please, try to update the tensorflow version, after it the code should work. I will fix the requirements list.

**Comment by EricRoberts714** [comment]
I reinstalled once again and the same error persists. Tensorflow and tensorflow-base versions are 1.14.0.

**Comment by flavio86** [comment]
Please, try to update tensorflow manually inside the virtual environment:
pip install --upgrade tensorflow  or 
conda update -f -c conda-forge tensorflow

**Comment by EricRoberts714** [comment]
Following error occurs after a manual tensorflow update:

![tensorflow-update_error](https://user-images.githubusercontent.com/17167333/72300215-f8878480-3617-11ea-92c1-78375d7c6071.png)

Tensorflow version:

![tensorflow_vers](https://user-images.githubusercontent.com/17167333/72300227-04734680-3618-11ea-916e-9149f7933427.png)
